
index:
    path:     /
    defaults: { _controller: OSUAppBundle:Index:index }

admission:
    path:     /admission
    defaults: { _controller: OSUAppBundle:Admission:admission }

tuition:
    path:     /tuition
    defaults: { _controller: OSUAppBundle:Tuition:tuition }

courses:
    path:     /courses
    defaults: { _controller: OSUAppBundle:Courses:courses }

representatives:
    path:     /representatives
    defaults: { _controller: OSUAppBundle:Representatives:representatives }

contact:
    path:     /contact
    defaults: { _controller: OSUAppBundle:Contacts:contact }

sendmail:
    path: /contacts/send/mail
    defaults: { _controller: OSUAppBundle:Contacts:sendMail }
    methods: POST

dean:
    path:     /dean
    defaults: { _controller: OSUAppBundle:Dean:dean }

posts:
    path:     /posts
    defaults: { _controller: OSUAppBundle:Posts:posts }

post:
    path:     /post/{id}
    defaults: { _controller: OSUAppBundle:Posts:post }

relationship:
    path:     /relationship
    defaults: { _controller: OSUAppBundle:Relationship:relationship }

hostels:
    path:     /hostels
    defaults: { _controller: OSUAppBundle:Hostels:hostels }

galleries:
    path:     /galleries
    defaults: { _controller: OSUAppBundle:Gallery:galleries }

gallery:
    path:     /gallery/{id}
    defaults: { _controller: OSUAppBundle:Gallery:gallery }

travel:
    path:     /travel
    defaults: { _controller: OSUAppBundle:Travel:travel }

questions:
    path:     /FAQ
    defaults: { _controller: OSUAppBundle:FAQ:questions }

history:
    path:     /osh-state-university/history
    defaults: { _controller: OSUAppBundle:History:history }

rector:
    path:     /message-from-rector
    defaults: { _controller: OSUAppBundle:Rector:rector }

students_live:
    path:     /students-live
    defaults: { _controller: OSUAppBundle:Students:studentsLive }
